# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optimus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='optimus.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\roptimus.proto\"\xf3\x01\n\x03Job\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x1b\n\x06status\x18\x03 \x01(\x0e\x32\x0b.Job.Status\x12\x12\n\ncoordinate\x18\x04 \x01(\t\x12\x14\n\x0cmetric_value\x18\x05 \x01(\t\x12\x10\n\x08metadata\x18\x06 \x01(\t\x12\r\n\x05input\x18\x07 \x01(\t\x12\x0e\n\x06output\x18\x08 \x01(\t\x12\x0c\n\x04kind\x18\t \x01(\t\"I\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\n\n\x06PULLED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x12\r\n\tCOMPLETED\x10\x04\" \n\nListOfJobs\x12\x12\n\x04jobs\x18\x01 \x03(\x0b\x32\x04.Job\"\x1b\n\rRequestWithId\x12\n\n\x02id\x18\x01 \x01(\x04\"#\n\x0fListJobsRequest\x12\x10\n\x08how_many\x18\x01 \x01(\r2\xf4\x01\n\x07Optimus\x12\x19\n\tCreateJob\x12\x04.Job\x1a\x04.Job\"\x00\x12\x30\n\x12\x43reateMultipleJobs\x12\x0b.ListOfJobs\x1a\x0b.ListOfJobs\"\x00\x12 \n\x06GetJob\x12\x0e.RequestWithId\x1a\x04.Job\"\x00\x12+\n\x08ListJobs\x12\x10.ListJobsRequest\x1a\x0b.ListOfJobs\"\x00\x12\x19\n\tModifyJob\x12\x04.Job\x1a\x04.Job\"\x00\x12\x32\n\x0fPullPendingJobs\x12\x10.ListJobsRequest\x1a\x0b.ListOfJobs\"\x00\x62\x06proto3')
)



_JOB_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Job.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PULLED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=188,
  serialized_end=261,
)
_sym_db.RegisterEnumDescriptor(_JOB_STATUS)


_JOB = _descriptor.Descriptor(
  name='Job',
  full_name='Job',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='project', full_name='Job.project', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Job.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Job.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='Job.coordinate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_value', full_name='Job.metric_value', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='Job.metadata', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='Job.input', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='Job.output', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kind', full_name='Job.kind', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOB_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=261,
)


_LISTOFJOBS = _descriptor.Descriptor(
  name='ListOfJobs',
  full_name='ListOfJobs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobs', full_name='ListOfJobs.jobs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=295,
)


_REQUESTWITHID = _descriptor.Descriptor(
  name='RequestWithId',
  full_name='RequestWithId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RequestWithId.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=324,
)


_LISTJOBSREQUEST = _descriptor.Descriptor(
  name='ListJobsRequest',
  full_name='ListJobsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='how_many', full_name='ListJobsRequest.how_many', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=361,
)

_JOB.fields_by_name['status'].enum_type = _JOB_STATUS
_JOB_STATUS.containing_type = _JOB
_LISTOFJOBS.fields_by_name['jobs'].message_type = _JOB
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['ListOfJobs'] = _LISTOFJOBS
DESCRIPTOR.message_types_by_name['RequestWithId'] = _REQUESTWITHID
DESCRIPTOR.message_types_by_name['ListJobsRequest'] = _LISTJOBSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), dict(
  DESCRIPTOR = _JOB,
  __module__ = 'optimus_pb2'
  # @@protoc_insertion_point(class_scope:Job)
  ))
_sym_db.RegisterMessage(Job)

ListOfJobs = _reflection.GeneratedProtocolMessageType('ListOfJobs', (_message.Message,), dict(
  DESCRIPTOR = _LISTOFJOBS,
  __module__ = 'optimus_pb2'
  # @@protoc_insertion_point(class_scope:ListOfJobs)
  ))
_sym_db.RegisterMessage(ListOfJobs)

RequestWithId = _reflection.GeneratedProtocolMessageType('RequestWithId', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTWITHID,
  __module__ = 'optimus_pb2'
  # @@protoc_insertion_point(class_scope:RequestWithId)
  ))
_sym_db.RegisterMessage(RequestWithId)

ListJobsRequest = _reflection.GeneratedProtocolMessageType('ListJobsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTJOBSREQUEST,
  __module__ = 'optimus_pb2'
  # @@protoc_insertion_point(class_scope:ListJobsRequest)
  ))
_sym_db.RegisterMessage(ListJobsRequest)



_OPTIMUS = _descriptor.ServiceDescriptor(
  name='Optimus',
  full_name='Optimus',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=364,
  serialized_end=608,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateJob',
    full_name='Optimus.CreateJob',
    index=0,
    containing_service=None,
    input_type=_JOB,
    output_type=_JOB,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateMultipleJobs',
    full_name='Optimus.CreateMultipleJobs',
    index=1,
    containing_service=None,
    input_type=_LISTOFJOBS,
    output_type=_LISTOFJOBS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJob',
    full_name='Optimus.GetJob',
    index=2,
    containing_service=None,
    input_type=_REQUESTWITHID,
    output_type=_JOB,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListJobs',
    full_name='Optimus.ListJobs',
    index=3,
    containing_service=None,
    input_type=_LISTJOBSREQUEST,
    output_type=_LISTOFJOBS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ModifyJob',
    full_name='Optimus.ModifyJob',
    index=4,
    containing_service=None,
    input_type=_JOB,
    output_type=_JOB,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PullPendingJobs',
    full_name='Optimus.PullPendingJobs',
    index=5,
    containing_service=None,
    input_type=_LISTJOBSREQUEST,
    output_type=_LISTOFJOBS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPTIMUS)

DESCRIPTOR.services_by_name['Optimus'] = _OPTIMUS

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class OptimusStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.CreateJob = channel.unary_unary(
          '/Optimus/CreateJob',
          request_serializer=Job.SerializeToString,
          response_deserializer=Job.FromString,
          )
      self.CreateMultipleJobs = channel.unary_unary(
          '/Optimus/CreateMultipleJobs',
          request_serializer=ListOfJobs.SerializeToString,
          response_deserializer=ListOfJobs.FromString,
          )
      self.GetJob = channel.unary_unary(
          '/Optimus/GetJob',
          request_serializer=RequestWithId.SerializeToString,
          response_deserializer=Job.FromString,
          )
      self.ListJobs = channel.unary_unary(
          '/Optimus/ListJobs',
          request_serializer=ListJobsRequest.SerializeToString,
          response_deserializer=ListOfJobs.FromString,
          )
      self.ModifyJob = channel.unary_unary(
          '/Optimus/ModifyJob',
          request_serializer=Job.SerializeToString,
          response_deserializer=Job.FromString,
          )
      self.PullPendingJobs = channel.unary_unary(
          '/Optimus/PullPendingJobs',
          request_serializer=ListJobsRequest.SerializeToString,
          response_deserializer=ListOfJobs.FromString,
          )


  class OptimusServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def CreateJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def CreateMultipleJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def ModifyJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def PullPendingJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_OptimusServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateJob': grpc.unary_unary_rpc_method_handler(
            servicer.CreateJob,
            request_deserializer=Job.FromString,
            response_serializer=Job.SerializeToString,
        ),
        'CreateMultipleJobs': grpc.unary_unary_rpc_method_handler(
            servicer.CreateMultipleJobs,
            request_deserializer=ListOfJobs.FromString,
            response_serializer=ListOfJobs.SerializeToString,
        ),
        'GetJob': grpc.unary_unary_rpc_method_handler(
            servicer.GetJob,
            request_deserializer=RequestWithId.FromString,
            response_serializer=Job.SerializeToString,
        ),
        'ListJobs': grpc.unary_unary_rpc_method_handler(
            servicer.ListJobs,
            request_deserializer=ListJobsRequest.FromString,
            response_serializer=ListOfJobs.SerializeToString,
        ),
        'ModifyJob': grpc.unary_unary_rpc_method_handler(
            servicer.ModifyJob,
            request_deserializer=Job.FromString,
            response_serializer=Job.SerializeToString,
        ),
        'PullPendingJobs': grpc.unary_unary_rpc_method_handler(
            servicer.PullPendingJobs,
            request_deserializer=ListJobsRequest.FromString,
            response_serializer=ListOfJobs.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Optimus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaOptimusServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def CreateMultipleJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ListJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def ModifyJob(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def PullPendingJobs(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaOptimusStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def CreateJob(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    CreateJob.future = None
    def CreateMultipleJobs(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    CreateMultipleJobs.future = None
    def GetJob(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    GetJob.future = None
    def ListJobs(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    ListJobs.future = None
    def ModifyJob(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    ModifyJob.future = None
    def PullPendingJobs(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    PullPendingJobs.future = None


  def beta_create_Optimus_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Optimus', 'CreateJob'): Job.FromString,
      ('Optimus', 'CreateMultipleJobs'): ListOfJobs.FromString,
      ('Optimus', 'GetJob'): RequestWithId.FromString,
      ('Optimus', 'ListJobs'): ListJobsRequest.FromString,
      ('Optimus', 'ModifyJob'): Job.FromString,
      ('Optimus', 'PullPendingJobs'): ListJobsRequest.FromString,
    }
    response_serializers = {
      ('Optimus', 'CreateJob'): Job.SerializeToString,
      ('Optimus', 'CreateMultipleJobs'): ListOfJobs.SerializeToString,
      ('Optimus', 'GetJob'): Job.SerializeToString,
      ('Optimus', 'ListJobs'): ListOfJobs.SerializeToString,
      ('Optimus', 'ModifyJob'): Job.SerializeToString,
      ('Optimus', 'PullPendingJobs'): ListOfJobs.SerializeToString,
    }
    method_implementations = {
      ('Optimus', 'CreateJob'): face_utilities.unary_unary_inline(servicer.CreateJob),
      ('Optimus', 'CreateMultipleJobs'): face_utilities.unary_unary_inline(servicer.CreateMultipleJobs),
      ('Optimus', 'GetJob'): face_utilities.unary_unary_inline(servicer.GetJob),
      ('Optimus', 'ListJobs'): face_utilities.unary_unary_inline(servicer.ListJobs),
      ('Optimus', 'ModifyJob'): face_utilities.unary_unary_inline(servicer.ModifyJob),
      ('Optimus', 'PullPendingJobs'): face_utilities.unary_unary_inline(servicer.PullPendingJobs),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Optimus_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Optimus', 'CreateJob'): Job.SerializeToString,
      ('Optimus', 'CreateMultipleJobs'): ListOfJobs.SerializeToString,
      ('Optimus', 'GetJob'): RequestWithId.SerializeToString,
      ('Optimus', 'ListJobs'): ListJobsRequest.SerializeToString,
      ('Optimus', 'ModifyJob'): Job.SerializeToString,
      ('Optimus', 'PullPendingJobs'): ListJobsRequest.SerializeToString,
    }
    response_deserializers = {
      ('Optimus', 'CreateJob'): Job.FromString,
      ('Optimus', 'CreateMultipleJobs'): ListOfJobs.FromString,
      ('Optimus', 'GetJob'): Job.FromString,
      ('Optimus', 'ListJobs'): ListOfJobs.FromString,
      ('Optimus', 'ModifyJob'): Job.FromString,
      ('Optimus', 'PullPendingJobs'): ListOfJobs.FromString,
    }
    cardinalities = {
      'CreateJob': cardinality.Cardinality.UNARY_UNARY,
      'CreateMultipleJobs': cardinality.Cardinality.UNARY_UNARY,
      'GetJob': cardinality.Cardinality.UNARY_UNARY,
      'ListJobs': cardinality.Cardinality.UNARY_UNARY,
      'ModifyJob': cardinality.Cardinality.UNARY_UNARY,
      'PullPendingJobs': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Optimus', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
